version: "3.1"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3,cloudformation,sts,apigateway,iam,route53
      - EXTRA_CORS_ALLOWED_HEADERS=X-Referer, x-referer, Autorization, Origin, origin, X-Requested-With, X-Csrftoken, Content-Type, Accept, sec-ch-ua, sec-ch-ua-mobile, User-Agent
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"