service: lambda-node-mysql-docker

useDotenv: true

plugins:
    - serverless-offline

frameworkVersion: "2"

provider:
    name: aws
    runtime: nodejs14.x
    lambdaHashingVersion: 20201221

functions:
    list:
        handler: app/index.list
        events:
            - http:
                  path: todos
                  method: get
                  cors: true
    show:
        handler: app/index.show
        events:
            - http:
                  path: todos/{id}
                  method: get
                  cors: true
    add:
        handler: app/index.add
        events:
            - http:
                  path: todos
                  method: post
                  cors: true
    destroy:
        handler: app/index.destroy
        events:
            - http:
                  path: todos/{id}
                  method: delete
                  cors: true
